
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: history
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  clustering_app:
    build: .
    ports:
      - "7860:7860"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=history
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db



volumes:
  pg_data:
