
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mnist_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  clustering_app:
    build: .
    ports:
      - "7860:7860"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=mnist_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db

  seed_db:
    build: .
    command: python -m scripts.seed_db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=mnist_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db
    # seed_db завершится после выполнения скрипта

volumes:
  pg_data:
